SET ECHO ON
SPOOL mh_schema_output.txt

--STUDENT_ID: 30281229
--STUDENT_NAME: DEEPALI VINAY

-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-05-01 16:36:18 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP SEQUENCE adm_adm_num_seq;

DROP SEQUENCE adm_pro_adm_pro_num_seq;

DROP SEQUENCE bed_ward_code_seq;

DROP SEQUENCE cost_centre_cost_centre_code ;

DROP SEQUENCE doctor_doctor_id_seq;

DROP SEQUENCE nurse_nurse_id_seq;

DROP SEQUENCE patient_pat_id_seq;

DROP SEQUENCE procedure_procedure_code_seq;

DROP SEQUENCE ward_ward_code_seq;


DROP TABLE adm CASCADE CONSTRAINTS;

DROP TABLE adm_pro CASCADE CONSTRAINTS;

DROP TABLE bed CASCADE CONSTRAINTS;

DROP TABLE bed_assign CASCADE CONSTRAINTS;

DROP TABLE cost_centre CASCADE CONSTRAINTS;

DROP TABLE doc_spec CASCADE CONSTRAINTS;

DROP TABLE doctor CASCADE CONSTRAINTS;

DROP TABLE item CASCADE CONSTRAINTS;

DROP TABLE item_req CASCADE CONSTRAINTS;

DROP TABLE nurse CASCADE CONSTRAINTS;

DROP TABLE patient CASCADE CONSTRAINTS;

DROP TABLE procedure CASCADE CONSTRAINTS;

DROP TABLE spec CASCADE CONSTRAINTS;

DROP TABLE ward CASCADE CONSTRAINTS;

DROP TABLE ward_assign CASCADE CONSTRAINTS;

CREATE TABLE adm (
    adm_num               NUMBER(7) NOT NULL,
    pat_id                NUMBER(7) NOT NULL,
    adm_date_time         DATE NOT NULL,
    discharge_date_time   DATE,
    doctor_id             NUMBER(7) NOT NULL
);

ALTER TABLE adm ADD CONSTRAINT "admission_num check" CHECK ( adm_num > 0 );

COMMENT ON COLUMN adm.adm_num IS
    'Admission number-Surrogate key for admission entity';

COMMENT ON COLUMN adm.pat_id IS
    'Patient ID - Primary key of PATIENT entity';

COMMENT ON COLUMN adm.adm_date_time IS
    'Date and time of admission of a patient';

COMMENT ON COLUMN adm.discharge_date_time IS
    'Date and time of discharge';

COMMENT ON COLUMN adm.doctor_id IS
    'Doctor ID - Primary key of DOCTOR entity';

ALTER TABLE adm ADD CONSTRAINT adm_pk PRIMARY KEY ( adm_num );

ALTER TABLE adm ADD CONSTRAINT adm_pat_id_adm_date_time_un UNIQUE ( pat_id,
                                                                    adm_date_time
                                                                    );

CREATE TABLE adm_pro (
    adm_pro_num           NUMBER(7) NOT NULL,
    adm_num               NUMBER(7) NOT NULL,
    carr_out_on           DATE NOT NULL,
    procedure_charge      NUMBER(10, 2),
    total_extras_charge   NUMBER(10, 2),
    procedure_code        NUMBER(7) NOT NULL,
    doctor_id1            NUMBER(7) NOT NULL,
    doctor_id             NUMBER(7)
);

ALTER TABLE adm_pro ADD CONSTRAINT "adm_pro_num check" CHECK ( adm_pro_num > 0 )

;

COMMENT ON COLUMN adm_pro.adm_pro_num IS
    'Admission_Procedure_number-Surrogate key for adm-pro entity';

COMMENT ON COLUMN adm_pro.adm_num IS
    'Admission number-Surrogate key for admission entity';

COMMENT ON COLUMN adm_pro.carr_out_on IS
    'Carried out on - Date and time of procedure performed';

COMMENT ON COLUMN adm_pro.procedure_charge IS
    'Charge of procedure';

COMMENT ON COLUMN adm_pro.total_extras_charge IS
    'total charge of extra items';

COMMENT ON COLUMN adm_pro.procedure_code IS
    'Procedure code - Primary key';

COMMENT ON COLUMN adm_pro.doctor_id1 IS
    'Doctor ID - Primary key of DOCTOR entity';

COMMENT ON COLUMN adm_pro.doctor_id IS
    'Doctor ID - Primary key of DOCTOR entity';

ALTER TABLE adm_pro ADD CONSTRAINT adm_pro_pk PRIMARY KEY ( adm_pro_num );

ALTER TABLE adm_pro ADD CONSTRAINT adm_pro_carr_out_on_adm_num_un UNIQUE ( carr_out_on

,
                                                                           adm_num
                                                                           );

CREATE TABLE bed (
    ward_code          NUMBER(7) NOT NULL,
    bed_number         NUMBER(7) NOT NULL,
    telephone_number   NUMBER(12),
    bed_type           VARCHAR2(20) NOT NULL
);

ALTER TABLE bed ADD CONSTRAINT "bed_number check" CHECK ( bed_number > 0 );

ALTER TABLE bed
    ADD CONSTRAINT "Type of bed" CHECK ( bed_type IN (
        'Adjustable',
        'Fixed'
    ) );

COMMENT ON COLUMN bed.ward_code IS
    'Ward code - Primary key';

COMMENT ON COLUMN bed.bed_number IS
    'Bed number';

COMMENT ON COLUMN bed.telephone_number IS
    'Bedside telephone number';

COMMENT ON COLUMN bed.bed_type IS
    'Bed type';

ALTER TABLE bed ADD CONSTRAINT bed_pk PRIMARY KEY ( ward_code,
                                                    bed_number );

CREATE TABLE bed_assign (
    adm_num                    NUMBER(7) NOT NULL,
    bed_assignment_date_time   DATE NOT NULL,
    ward_code                  NUMBER(7) NOT NULL,
    bed_number                 NUMBER(7) NOT NULL
);

COMMENT ON COLUMN bed_assign.adm_num IS
    'Admission number-Surrogate key for admission entity';

COMMENT ON COLUMN bed_assign.bed_assignment_date_time IS
    'Bed assignment date and time';

COMMENT ON COLUMN bed_assign.ward_code IS
    'Ward code - Primary key';

COMMENT ON COLUMN bed_assign.bed_number IS
    'Bed number';

ALTER TABLE bed_assign ADD CONSTRAINT bed_assign_pk PRIMARY KEY ( bed_assignment_date_time
,
                                                                  adm_num );

CREATE TABLE cost_centre (
    cost_centre_code    NUMBER(7) NOT NULL,
    cost_centre_title   VARCHAR2(50),
    manager_name        VARCHAR2(50)
);

ALTER TABLE cost_centre ADD CONSTRAINT cost_centre_code CHECK ( cost_centre_code

> 0 );

COMMENT ON COLUMN cost_centre.cost_centre_code IS
    'Cost centre code - Primery key of the entity';

COMMENT ON COLUMN cost_centre.cost_centre_title IS
    'Title of cost centre';

COMMENT ON COLUMN cost_centre.manager_name IS
    'Name of manager';

ALTER TABLE cost_centre ADD CONSTRAINT cost_centre_pk PRIMARY KEY ( cost_centre_code
);

CREATE TABLE doc_spec (
    doctor_id        NUMBER(7) NOT NULL,
    specialisation   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN doc_spec.doctor_id IS
    'Doctor ID - Primary key of DOCTOR entity';

COMMENT ON COLUMN doc_spec.specialisation IS
    'Specialisation type';

ALTER TABLE doc_spec ADD CONSTRAINT doc_spec_pk PRIMARY KEY ( doctor_id,
                                                              specialisation );

CREATE TABLE doctor (
    doctor_id             NUMBER(7) NOT NULL,
    doctor_first_name     VARCHAR2(50) NOT NULL,
    doctor_last_name      VARCHAR2(50) NOT NULL,
    doctor_phone_number   NUMBER(12) NOT NULL
);

ALTER TABLE doctor ADD CONSTRAINT "doctor_id check" CHECK ( doctor_id > 0 );

COMMENT ON COLUMN doctor.doctor_id IS
    'Doctor ID - Primary key of DOCTOR entity';

COMMENT ON COLUMN doctor.doctor_first_name IS
    'Doctor''s first name';

COMMENT ON COLUMN doctor.doctor_last_name IS
    'Doctor''s last name';

COMMENT ON COLUMN doctor.doctor_phone_number IS
    'Doctor''s phone number';

ALTER TABLE doctor ADD CONSTRAINT doctor_pk PRIMARY KEY ( doctor_id );

CREATE TABLE item (
    item_code          VARCHAR2(10) NOT NULL,
    item_description   VARCHAR2(50) NOT NULL,
    current_stock      NUMBER(20) NOT NULL,
    price              NUMBER(10, 2) NOT NULL,
    cost_centre_code   NUMBER(7) NOT NULL
);

COMMENT ON COLUMN item.item_code IS
    'Item code - Primary key of ITEM entity';

COMMENT ON COLUMN item.item_description IS
    'Description of item';

COMMENT ON COLUMN item.current_stock IS
    'Current available stock of item';

COMMENT ON COLUMN item.price IS
    'Price of item';

COMMENT ON COLUMN item.cost_centre_code IS
    'Cost centre code - Primery key of the entity';

ALTER TABLE item ADD CONSTRAINT item_pk PRIMARY KEY ( item_code );

CREATE TABLE item_req (
    item_code           VARCHAR2(10) NOT NULL,
    adm_pro_num         NUMBER(7) NOT NULL,
    quantity            NUMBER(10),
    total_item_charge   NUMBER(10, 2)
);

COMMENT ON COLUMN item_req.item_code IS
    'Item code - Primary key of ITEM entity';

COMMENT ON COLUMN item_req.adm_pro_num IS
    'Admission_Procedure_number-Surrogate key for adm-pro entity';

COMMENT ON COLUMN item_req.quantity IS
    'Quantity of item used';

COMMENT ON COLUMN item_req.total_item_charge IS
    'Charge of each type of item used';

ALTER TABLE item_req ADD CONSTRAINT item_req_pk PRIMARY KEY ( item_code,
                                                              adm_pro_num );

CREATE TABLE nurse (
    nurse_id          NUMBER(7) NOT NULL,
    nurse_firstname   VARCHAR2(50) NOT NULL,
    nurse_lastname    VARCHAR2(50) NOT NULL,
    nurse_contact     NUMBER(12) NOT NULL,
    nurse_certified   CHAR(3) NOT NULL
);

ALTER TABLE nurse ADD CONSTRAINT "nurse_id check" CHECK ( nurse_id > 0 );

ALTER TABLE nurse
    ADD CONSTRAINT "Nurse Certification" CHECK ( nurse_certified IN (
        'No',
        'Yes'
    ) );

COMMENT ON COLUMN nurse.nurse_id IS
    'Nurse ID';

COMMENT ON COLUMN nurse.nurse_firstname IS
    'Nurse''s first name';

COMMENT ON COLUMN nurse.nurse_lastname IS
    'Nurse''s last name';

COMMENT ON COLUMN nurse.nurse_contact IS
    'Nurse''s contact number';

COMMENT ON COLUMN nurse.nurse_certified IS
    'Nurse certified for work with children';

ALTER TABLE nurse ADD CONSTRAINT nurse_pk PRIMARY KEY ( nurse_id );

CREATE TABLE patient (
    pat_id                  NUMBER(7) NOT NULL,
    patient_first_name      VARCHAR2(50) NOT NULL,
    patient_last_name       VARCHAR2(50) NOT NULL,
    patient_address         VARCHAR2(50),
    date_of_birth           DATE NOT NULL,
    emergency_contact_num   NUMBER(12) NOT NULL
);

ALTER TABLE patient ADD CONSTRAINT "patient_id check" CHECK ( pat_id > 0 );

COMMENT ON COLUMN patient.pat_id IS
    'Patient ID - Primary key of PATIENT entity';

COMMENT ON COLUMN patient.patient_first_name IS
    'Patient''s first name';

COMMENT ON COLUMN patient.patient_last_name IS
    'Patient''s last name';

COMMENT ON COLUMN patient.patient_address IS
    'Patient''s address';

COMMENT ON COLUMN patient.date_of_birth IS
    'Patient''s date of birth';

COMMENT ON COLUMN patient.emergency_contact_num IS
    'Patient''s emergency contact number';

ALTER TABLE patient ADD CONSTRAINT patient_pk PRIMARY KEY ( pat_id );

CREATE TABLE procedure (
    procedure_code          NUMBER(7) NOT NULL,
    procedure_name          VARCHAR2(50) NOT NULL,
    procedure_description   VARCHAR2(50),
    time_required           DATE NOT NULL
);

ALTER TABLE procedure ADD CONSTRAINT "procedure_code check" CHECK ( procedure_code

> 0 );

COMMENT ON COLUMN procedure.procedure_code IS
    'Procedure code - Primary key';

COMMENT ON COLUMN procedure.procedure_name IS
    'Name of Procedure';

COMMENT ON COLUMN procedure.procedure_description IS
    'Description of procedure';

COMMENT ON COLUMN procedure.time_required IS
    'Duration of procedure';

ALTER TABLE procedure ADD CONSTRAINT procedure_pk PRIMARY KEY ( procedure_code );

CREATE TABLE spec (
    specialisation VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN spec.specialisation IS
    'Specialisation type';

ALTER TABLE spec ADD CONSTRAINT spec_pk PRIMARY KEY ( specialisation );

CREATE TABLE ward (
    ward_code        NUMBER(7) NOT NULL,
    ward_name        VARCHAR2(50) NOT NULL,
    total_bed_num    NUMBER(10) NOT NULL,
    available_beds   NUMBER(10) NOT NULL
);

ALTER TABLE ward ADD CONSTRAINT "ward_code check" CHECK ( ward_code > 0 );

COMMENT ON COLUMN ward.ward_code IS
    'Ward code - Primary key';

COMMENT ON COLUMN ward.ward_name IS
    'Name of ward';

COMMENT ON COLUMN ward.total_bed_num IS
    'Total number of beds';

COMMENT ON COLUMN ward.available_beds IS
    'Number of beds available';

ALTER TABLE ward ADD CONSTRAINT ward_pk PRIMARY KEY ( ward_code );

CREATE TABLE ward_assign (
    nurse_id              NUMBER(7) NOT NULL,
    ward_assigned_date    DATE NOT NULL,
    ward_date_completed   DATE NOT NULL,
    ward_code             NUMBER(7) NOT NULL
);

COMMENT ON COLUMN ward_assign.nurse_id IS
    'Nurse ID';

COMMENT ON COLUMN ward_assign.ward_assigned_date IS
    'Assignment date of ward';

COMMENT ON COLUMN ward_assign.ward_date_completed IS
    'Completion date of ward assignment';

COMMENT ON COLUMN ward_assign.ward_code IS
    'Ward code - Primary key';

ALTER TABLE ward_assign ADD CONSTRAINT ward_assign_pk PRIMARY KEY ( nurse_id,
                                                                    ward_assigned_date
                                                                    );

ALTER TABLE adm
    ADD CONSTRAINT adm_doctor_fk FOREIGN KEY ( doctor_id )
        REFERENCES doctor ( doctor_id );

ALTER TABLE adm
    ADD CONSTRAINT adm_patient_fk FOREIGN KEY ( pat_id )
        REFERENCES patient ( pat_id );

ALTER TABLE adm_pro
    ADD CONSTRAINT adm_pro_adm_fk FOREIGN KEY ( adm_num )
        REFERENCES adm ( adm_num );

ALTER TABLE adm_pro
    ADD CONSTRAINT adm_pro_doctor_fk FOREIGN KEY ( doctor_id )
        REFERENCES doctor ( doctor_id );

ALTER TABLE adm_pro
    ADD CONSTRAINT adm_pro_doctor_fkv2 FOREIGN KEY ( doctor_id1 )
        REFERENCES doctor ( doctor_id );

ALTER TABLE adm_pro
    ADD CONSTRAINT adm_pro_procedure_fk FOREIGN KEY ( procedure_code )
        REFERENCES procedure ( procedure_code );

ALTER TABLE bed_assign
    ADD CONSTRAINT bed_assign_adm_fk FOREIGN KEY ( adm_num )
        REFERENCES adm ( adm_num );

ALTER TABLE bed_assign
    ADD CONSTRAINT bed_assign_bed_fk FOREIGN KEY ( ward_code,
                                                   bed_number )
        REFERENCES bed ( ward_code,
                         bed_number );

ALTER TABLE bed
    ADD CONSTRAINT bed_ward_fk FOREIGN KEY ( ward_code )
        REFERENCES ward ( ward_code );

ALTER TABLE doc_spec
    ADD CONSTRAINT doc_spec_doctor_fk FOREIGN KEY ( doctor_id )
        REFERENCES doctor ( doctor_id );

ALTER TABLE doc_spec
    ADD CONSTRAINT doc_spec_spec_fk FOREIGN KEY ( specialisation )
        REFERENCES spec ( specialisation );

ALTER TABLE item
    ADD CONSTRAINT item_cost_centre_fk FOREIGN KEY ( cost_centre_code )
        REFERENCES cost_centre ( cost_centre_code );

ALTER TABLE item_req
    ADD CONSTRAINT item_req_adm_pro_fk FOREIGN KEY ( adm_pro_num )
        REFERENCES adm_pro ( adm_pro_num );

ALTER TABLE item_req
    ADD CONSTRAINT item_req_item_fk FOREIGN KEY ( item_code )
        REFERENCES item ( item_code );

ALTER TABLE ward_assign
    ADD CONSTRAINT ward_assign_nurse_fk FOREIGN KEY ( nurse_id )
        REFERENCES nurse ( nurse_id );

ALTER TABLE ward_assign
    ADD CONSTRAINT ward_assign_ward_fk FOREIGN KEY ( ward_code )
        REFERENCES ward ( ward_code );





-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             44
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          9
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SET ECHO OFF
SPOOL OFF